backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

media_folder: static/img
public_folder: /img

i18n:
  structure: multiple_folders
  locales: [en, pa]

collections:
  - label: 'Pages'
    name: 'pages'
    delete: false # Prevent users from deleting documents in this collection
    i18n:
      structure: single_file
    files:
      - name: 'home'
        label: 'Home Page'
        file: 'content/home.json'
        format: 'frontmatter'
        i18n: true
        fields:
          - {
              label: 'Main Message by Babaji',
              name: 'main',
              widget: 'markdown',
              i18n: true,
            }
