backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

media_folder: static/img
public_folder: /img
local_backend: true

i18n:
  structure: multiple_folders
  locales: [en, pa]

collections:
  - label: 'Website Content'
    name: 'content'
    delete: false # Prevent users from deleting documents in this collection
    i18n:
      structure: single_file
    files:
      - name: 'home_texts'
        label: 'Home Page Texts'
        file: 'content/home_texts.json'
        i18n: true
        fields:
          - label: 'Gurbani line'
            name: 'gurbani_line'
            widget: 'string'
            i18n: true
          - label: 'Front message'
            name: 'front_message'
            widget: 'string'
            i18n: true
          - label: 'Main Message by Babaji'
            name: 'babaji_message'
            widget: 'object'
            i18n: true
            fields:
              - { label: 'Body', name: 'body', widget: 'text', i18n: true }
              - { label: 'Footer', name: 'footer', widget: 'text', i18n: true }
          - label: 'Testimonial Details'
            name: 'testimonial'
            widget: 'object'
            i18n: true
            fields:
              - { label: 'Body', name: 'body', widget: 'text', i18n: true }
              - { label: 'Footer', name: 'footer', widget: 'text', i18n: true }
              - {
                  label: 'Youtube Video Id',
                  name: 'yt_id',
                  widget: 'string',
                  i18n: duplicate,
                  hint: 'Please input valid youtube id. https://www.easterseals.com/assets/includes/youtube-id.html Available in EN only.',
                }
      - name: 'prachar_events'
        label: 'Prachar Events'
        file: 'content/prachar_events.json'
        i18n: true
        hint: 'Events would be displayed newest to oldest in the website, ignoring the order here'
        fields:
          - label: 'Events'
            name: 'events_list'
            widget: 'list'
            i18n: true
            fields:
              - {
                  label: 'Date',
                  name: 'date',
                  widget: 'datetime',
                  date_format: true,
                  time_format: false,
                  i18n: false,
                  hint: 'Please enter event date. Available in EN only.',
                }
              - {
                  label: 'Location',
                  name: 'location',
                  widget: 'string',
                  hint: 'Please enter event location. Non EN entries would be mapped to same order as EN.',
                  i18n: true,
                }
              - {
                  label: 'Event photo',
                  name: 'photo',
                  widget: 'image',
                  choose_url: false,
                  i18n: false,
                  hint: 'Please upload event photo. Prefer photos with 16:9 aspect ratio. Available in EN only.',
                }
