backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

media_folder: static/img
public_folder: /img

i18n:
  structure: multiple_folders
  locales: [en, pa]

collections:
  - label: 'Pages'
    name: 'pages'
    delete: false # Prevent users from deleting documents in this collection
    i18n:
      structure: single_file
    files:
      - name: 'home'
        label: 'Home Page'
        file: 'content/home.json'
        i18n:
          structure: single_file
        fields:
          - {label: "Has md text", name: "hasMd", widget: "hidden", default: true,i18n: false}
          - label: 'Main Message by Babaji',
            name: 'body',
            widget: 'object',
            collapsed: true,
            fields:
              - {label: "Body", name: "body", widget: "markdown", i18n: true}
              
