backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

media_folder: static/img
public_folder: /img

i18n:
  structure: multiple_folders
  locales: [en, pa]

collections:
  - label: 'Content'
    name: 'content'
    delete: false # Prevent users from deleting documents in this collection
    i18n:
      structure: single_file
    files:
      - name: 'main-en'
        label: 'Main Message by Babaji in English'
        file: 'content/main.en.md'
        format: 'frontmatter'
        i18n: false
        fields:
          - {
              label: 'Main Message by Babaji in English',
              name: 'main',
              widget: 'markdown',
            }
      - name: 'main-pa'
        label: 'Main Message by Babaji in Punjabi'
        file: 'content/main.pa.md'
        format: 'frontmatter'
        i18n: false
        fields:
          - {
              label: 'Main Message by Babaji in Punjabi',
              name: 'main',
              widget: 'markdown',
            }
